"""Deterministic, same-scale silhouette study; approval assets only."""
import json
from pathlib import Path

import bpy
from mathutils import Vector

OUT = Path(__file__).resolve().parents[3] / "docs/design/blended-wing-v5/outline-study"
OUT.mkdir(parents=True, exist_ok=True)
# Nose to tail along the right side; the opposite side is generated by reflection.
PROFILES = {
    "FIELD": [(0,-2),(.6,-1.65),(1.65,-.95),(3,.4),(3.12,.75),(2.6,1.12),(1.5,.95),(.7,1.62),(0,1.45)],
    "SCOUT": [(0,-1.9),(.4,-1.25),(.85,-.5),(4.25,.58),(4.5,.82),(3.8,1.0),(1.0,.5),(.4,1.65),(0,1.52)],
    "CARGO": [(0,-2.25),(.9,-2.04),(1.6,-1.15),(3.15,.1),(3.32,.7),(2.8,1.25),(1.65,1.38),(.95,1.97),(0,2.1)],
    "ENGINEER": [(0,-2.15),(.6,-1.8),(2.2,-1.0),(3.4,-.15),(3.5,.4),(2.6,.75),(1.45,.6),(.5,1.9),(0,2.02)],
    "SECURITY": [(0,-2.65),(.5,-1.65),(1.0,-.8),(3.15,1.25),(3.5,1.85),(2.7,1.62),(1.25,.8),(.45,1.28),(0,1.2)],
    "SALVAGE": [(0,-2.35),(.8,-2.15),(1.8,-1.5),(3.7,-.1),(3.85,.6),(3.3,1.12),(2.0,1.9),(.85,2.42),(0,2.38)],
}


def smooth_half(points):
    p = [Vector(v) for v in points]
    extended = [Vector((-p[1].x,p[1].y))] + p + [Vector((-p[-2].x,p[-2].y))]
    result = []
    for i in range(1,len(extended)-2):
        a,b,c,d = extended[i-1:i+3]
        for step in range(16):
            t=step/16
            q=.5*((2*b)+(-a+c)*t+(2*a-5*b+4*c-d)*t*t+(-a+3*b-3*c+d)*t*t*t)
            result.append((max(0,q.x),q.y))
    return result+[points[-1]]


def material(name,color):
    m=bpy.data.materials.new(name)
    m.use_nodes=True
    nodes=m.node_tree.nodes
    nodes.clear()
    emit=nodes.new('ShaderNodeEmission')
    emit.inputs['Color'].default_value=(*color,1)
    output=nodes.new('ShaderNodeOutputMaterial')
    m.node_tree.links.new(emit.outputs[0],output.inputs[0])
    return m


def label(text,x,y,size):
    bpy.ops.object.text_add(location=(x,y,.05))
    obj=bpy.context.object
    obj.data.body=text
    obj.data.align_x='CENTER'
    obj.data.size=size
    obj.data.materials.append(ink)


bpy.ops.object.select_all(action='SELECT')
bpy.ops.object.delete(use_global=False)
ink=material('Silhouette',(.025,.035,.04))
report=[]
for index,(role,points) in enumerate(PROFILES.items()):
    half=smooth_half(points)
    polygon=half+[(-x,y) for x,y in reversed(half[1:-1])]
    coords={(round(x,7),round(y,7)) for x,y in polygon}
    assert all((round(-x,7),round(y,7)) in coords for x,y in polygon)
    width=max(x for x,y in polygon)-min(x for x,y in polygon)
    length=max(y for x,y in polygon)-min(y for x,y in polygon)
    x=(index%3-1)*10.5
    y=4.0-(index//3)*8.0
    mesh=bpy.data.meshes.new(role)
    # Flip model forward -Y to image-up +Y; retain exact same scale for all roles.
    mesh.from_pydata([(px,-py,0) for px,py in polygon],[],[tuple(range(len(polygon)))])
    mesh.update()
    obj=bpy.data.objects.new(role,mesh)
    bpy.context.collection.objects.link(obj)
    obj.location=(x,y,0)
    obj.data.materials.append(ink)
    label(role,x,y-3.3,.52)
    label(f"W/L {width/length:.2f}   WIDTH {width/6.24:.2f}x",x,y-4,.28)
    report.append({'role':role,'width':width,'length':length,'widthLengthRatio':width/length,
                   'bilateralOutlinePass':True,'sameScale':True,'gameVerified':False})
label('MORROWGEAR / FLOW + ROLE',0,8,.55)
label('SAME SCALE / NO EQUIPMENT / NO COLOR CODING',0,7.25,.25)
scene=bpy.context.scene
scene.render.engine='BLENDER_EEVEE'
scene.world.use_nodes=True
scene.world.node_tree.nodes['Background'].inputs[0].default_value=(.78,.8,.81,1)
scene.world.node_tree.nodes['Background'].inputs[1].default_value=1
scene.view_settings.view_transform='Standard'
bpy.ops.object.camera_add(location=(0,0,30))
camera=bpy.context.object
camera.rotation_euler=(0,0,0)
camera.data.type='ORTHO'
camera.data.ortho_scale=32
scene.camera=camera
scene.render.resolution_x=1800
scene.render.resolution_y=1080
scene.render.resolution_percentage=100
scene.render.image_settings.file_format='PNG'
scene.render.filepath=str(OUT/'silhouettes.png')
bpy.ops.wm.save_as_mainfile(filepath=str(OUT/'outlines.blend'))
bpy.ops.render.render(write_still=True)
(OUT/'measurements.json').write_text(json.dumps(report,indent=2),encoding='utf-8')
print('OUTLINE_STUDY_COMPLETE')
